services:
  - type: web
    name: travel-agenet
    env: node
    plan: free
    branch: main
    autoDeploy: true
    pullRequestPreviewsEnabled: true
    buildCommand: npm ci
    startCommand: npm start
    healthCheckPath: /
    envVars:
      - key: OPENAI_API_KEY
        sync: false
